// Class automatically generated by Dev-C++ New Class wizard

#ifndef ENGINEAPI_H
#define ENGINEAPI_H

#include "assetparser.h"
#include "glapi.h"
#include "keyinputapi.h"

// No description
class EngineAPI
{
    private:
        bool shutdown;
        
	public:
        static EngineAPI& GetInstance() {
            static EngineAPI instance;
            return instance;
        }
        
        inline void StopEngine() { shutdown = true; }
        
        inline bool InternalGetShutdown() { return shutdown; }
        
    private:
        EngineAPI() : shutdown(false) { }
};

#endif // ENGINEAPI_H
