// Class automatically generated by Dev-C++ New Class wizard

#ifndef GAMEENGINELAUNCHER_H
#define GAMEENGINELAUNCHER_H

#include <windows.h>
#include "gameengine.h"

// This Class is not a singleton... but acts like a singleton
class GameEngineLauncher
{
    private:
        static bool launched;
        static GameEngineLauncher* instance;
        
    private:
        GameEngineInitializer param;
        HWND mainWnd;
        GameEngine& engine;
        HANDLE thread;
    
        static const char szClassName[ ];
        static const char wdTitleText[ ];
        static const char wdAboutTitle[ ];
        static const char wdAboutText[ ];
        
    public:
        GameEngineLauncher(GameEngine* instance, GameEngineInitializer init);
        int Launch();
        
    private:
        // Callbacks delegate functions
        inline static LRESULT CALLBACK EventHandlerEntry(HWND hwnd, UINT message, WPARAM wParam, LPARAM lParam);
        static DWORD WINAPI ThreadFixedUpdateEntry(LPVOID lpParam);
        
        // Callbacks
        LRESULT CALLBACK EventHandler(HWND hwnd, UINT message, WPARAM wParam, LPARAM lParam);
        DWORD ThreadFixedUpdate();
        
        // Launch Engine
        int InternalLaunch();
};

#endif // GAMEENGINELAUNCHER_H
