// Class automatically generated by Dev-C++ New Class wizard

#ifndef GAMEENGINEIMPL_H
#define GAMEENGINEIMPL_H

#include "gameengine.h" // inheriting class's header file
#include "samplescene.h"
#include "somegamescene.h"

// No description
class GameEngineImpl : public GameEngine
{
    private:
        SampleScene     sample;
        SomeGameScene   game;
    
    public:
        static GameEngine& GetInstance() {
            static GameEngineImpl instance;
            return instance;
        }
        
    protected:
        virtual void CustomInitialize();
        virtual void CustomOnEngineDestruct();
        
    private:
        GameEngineImpl() { }
        
};

#endif // GAMEENGINEIMPL_H
