// Class automatically generated by Dev-C++ New Class wizard

#ifndef MASTERSCENEOBJECT_H
#define MASTERSCENEOBJECT_H

#include "sceneobject.h" // inheriting class's header file

// Top Level Scene Object
class MasterSceneObject : public SceneObject
{
	public:
		virtual void Draw();
};

#endif // MASTERSCENEOBJECT_H
