// Class automatically generated by Dev-C++ New Class wizard

#include "mastersceneobject.h" // class's header file

void MasterSceneObject::Draw() {
    if (!enabled)   return;
    
    // Push Matrix
    gl.PushMatrix();
    
    // Transformation
    gl.TranslateMasterSO(transformation);
    
    // Draw Child Object
    vector<SceneObject*>& children = GetChildrenVector();
    vector<SceneObject*>::iterator iter;
    for (iter = children.begin(); iter != children.end(); iter++) {
        (*iter)->Draw();
    }
    
    // Pop Matrix
    gl.PopMatrix();
}
