// Class automatically generated by Dev-C++ New Class wizard

#include "physicsengine.h" // class's header file

// class constructor
PhysicsEngine::PhysicsEngine()
{
	// insert your code here
}

// class destructor
PhysicsEngine::~PhysicsEngine()
{
	// insert your code here
}

bool PhysicsEngine::CollisionCheckBox(const Vector2D& srccld, const Transformation& srctf,
                                      const Vector2D& refcld, const Transformation& reftf)
{
    
    // Learn About it  
    
    
}
