// Class automatically generated by Dev-C++ New Class wizard

#ifndef SAMPLESCENE_H
#define SAMPLESCENE_H

#include "scene.h" // inheriting class's header file

using namespace ki;

// No description
class SampleScene : public Scene
{
    private:
        // Named Texture Map
        NamedTextureStorage nts;
        
        // RenderObject
        RenderObject bg;
        RenderObject so1, so2, so3, so4, so5;
        TextObject   to;
        
        // Selected Object
        SceneObject* selected;
        
	public:
        void Initialize();
        
        virtual void OnBegin();
		virtual void OnEnd();
        
        virtual void OnFixedLoading();
		virtual void OnFixedUpdate();
		virtual void OnFixedClosing();
		
        virtual void OnLoading();
		virtual void OnUpdate();
		virtual void OnClosing();
		
    private:
        void CheckTransformationKey();
        void CheckObjectSwitchingKey();
        void CheckRenderOptionKey();
        void CheckEtcKey();
        
};

#endif // SAMPLESCENE_H
