// Class automatically generated by Dev-C++ New Class wizard

#ifndef SOMEGAME_H
#define SOMEGAME_H

#include "time.h"
#include "scene.h" // inheriting class's header file

using namespace ki;

// No description
class SomeGameScene : public Scene
{
    private:
        // Named Texture Map
        NamedTextureStorage nts;
        
        // Object
        SceneObject hidden;
        RenderObject fade;
        RenderObject bg;
        RenderObject player;
        
        // Vector
        vector<RenderObject*> enemy;
        
        // etc
        int frame;
        int tick, increment;
        int jump;
        bool gg;
        
	public:
        void Initialize();
        
        virtual void OnBegin();
		virtual void OnEnd();
        
		virtual void OnFixedUpdate();
        virtual void OnFixedLoading();
		virtual void OnFixedClosing();
		
        virtual void OnLoading();
		virtual void OnUpdate();
		virtual void OnClosing();
		
    private:
};

#endif // SOMEGAME_H
