// Class automatically generated by Dev-C++ New Class wizard

#include "textobject.h" // class's header file

TextObject::TextObject() : SceneObject() {
    this->tickPerChar = 1;
    SetText(" ");
}

void TextObject::SetText(string text) {
    this->text = text;
    this->length = strlen(text.c_str());
    Reset();
}

void TextObject::Reset() {
    begin = false;
    cursor = 0;
    tick = 0;
}

void TextObject::OnFixedUpdate() {
    if (begin) {
        // Move Cursor Forward
        if (tick % tickPerChar == 0) {
            
            if (cursor < length - 1) {
                if (text.at(cursor) & 0x80)
                    cursor += 2;
                else
                    cursor++;
                    
                if (cursor >= length - 1)
                    cursor = length - 1;
            }
        }
    }
}

void TextObject::Draw() {
    // Displaying Text Not Started yet
    if (!begin)
        return;
    
    // Push Matrix
    gl.PushMatrix();
    gl.Transform(transformation);
    
    // Draw String
    gl.DrawString(transformation, text, cursor);
    
    // Draw Child Object
    vector<SceneObject*>& children = GetChildrenVector();
    vector<SceneObject*>::iterator iter;
    for (iter = children.begin(); iter != children.end(); iter++) {
        (*iter)->Draw();
    }
    
    // Pop Matrix
    gl.PopMatrix();
}
