// Class automatically generated by Dev-C++ New Class wizard

#ifndef COLLIDER_H
#define COLLIDER_H

#include "datatype.h"

// No description
class Collider
{
    public:
        enum ColliderBody {
            Box,
            Circle,
            Point
        };
            
	public:
		bool enabled;
        ColliderBody body;
		Vector2D colliderSize;
		uint weight;
		Vector2D velocity;
		Vector2D acceleration;
		float torque;
		
    public:
        Collider() : enabled(false), body(Collider::Box) { }
        
};

#endif // COLLIDER_H
