// Class automatically generated by Dev-C++ New Class wizard

#include "gameenginebuilder.h" // class's header file

// class constructor
GameEngineBuilder::GameEngineBuilder(HINSTANCE hInstance, int nCmdShow)
{
    instance = NULL;
    param.hInstance = hInstance;
    param.nCmdShow = nCmdShow;
    param.windowSize = Point2D(800, 600);
    param.title = "RPG:ME";
    param.updateDelay = 62500;
    param.drawDelay = 62500;
    param.keepUpdateOnBackground = false;
    param.keepDrawOnBackground = false;
}

GameEngineBuilder& GameEngineBuilder::SetEngineInstance(GameEngine* instance) {
    this->instance = instance;
    return *this;
}

GameEngineBuilder& GameEngineBuilder::SetWindowSize(uint width, uint height) {
    param.windowSize = Point2D(width, height);
    return *this;
}

GameEngineBuilder& GameEngineBuilder::SetWindowTitle(string title) {
    param.title = title;
    return *this;
}

GameEngineBuilder& GameEngineBuilder::SetFixedUpdateDelay(uint micros) {
    param.updateDelay = micros;
    return *this;
}

GameEngineBuilder& GameEngineBuilder::SetUpdateDelay(uint micros) {
    param.drawDelay = micros;
    return *this;
}

GameEngineBuilder& GameEngineBuilder::EnableKeepUpdateOnBackground() {
    param.keepUpdateOnBackground = true;
    return *this;
}

GameEngineBuilder& GameEngineBuilder::EnableKeepDrawOnBackground() {
    param.keepDrawOnBackground = true;
    return *this;
}

GameEngineLauncher GameEngineBuilder::Build() {
    if (!this->instance)
        throw invalid_argument("Engine Instance is not set.");
    
    return GameEngineLauncher(instance, param);
}
