// Class automatically generated by Dev-C++ New Class wizard

#ifndef GAMEENGINEBUILDER_H
#define GAMEENGINEBUILDER_H

#include <stdexcept>
#include "gameenginelauncher.h"

// No description
class GameEngineBuilder
{
    private:
        GameEngine* instance;
        GameEngineInitializer param;
        
	public:
		// class constructor
		GameEngineBuilder(HINSTANCE hInstance, int nCmdShow);
		
		GameEngineBuilder& SetEngineInstance(GameEngine* instance);
		GameEngineBuilder& SetWindowSize(uint width, uint height);
		GameEngineBuilder& SetWindowTitle(string title);
		GameEngineBuilder& SetFixedUpdateDelay(uint micros);
		GameEngineBuilder& SetUpdateDelay(uint micros);
		GameEngineBuilder& EnableKeepUpdateOnBackground();
		GameEngineBuilder& EnableKeepDrawOnBackground();
		
		GameEngineLauncher Build();
};

#endif // GAMEENGINEBUILDER_H
