// Class automatically generated by Dev-C++ New Class wizard

#ifndef PHYSICSENGINE_H
#define PHYSICSENGINE_H

#include "datatype.h"

// No description
class PhysicsEngine
{
	public:
        bool CollisionCheckBox(const Vector2D& srccld, const Transformation& srctf,
                               const Vector2D& refcld, const Transformation& reftf);
        
        
		// class constructor
		PhysicsEngine();
		// class destructor
		~PhysicsEngine();
};

#endif // PHYSICSENGINE_H
