// Class automatically generated by Dev-C++ New Class wizard

#ifndef TEXTOBJECT_H
#define TEXTOBJECT_H

#include "sceneobject.h" // inheriting class's header file

// No description
class TextObject : public SceneObject
{
    private:
        string text;
        bool begin;
        uint length;
        uint cursor;
        uint tickPerChar;
    
	public:
        TextObject();
        void SetText(string text);
        inline void SetTickPerChar(uint tpc) { this->tickPerChar = tpc; }
        void Reset();
		inline void BeginDisplay() { begin = true; }
		inline void ForceEnd() { cursor = length - 1; }
		virtual void OnFixedUpdate(); 
        virtual void Draw();
};

#endif // TEXTOBJECT_H
